:hub_openshift_api_server_url: %hub_openshift_api_server_url%
:hub_openshift_cluster_console_url: %hub_openshift_cluster_console_url%
:hub_openshift_cluster_admin_username: %hub_openshift_cluster_admin_username%
:hub_openshift_cluster_admin_password: %hub_openshift_cluster_admin_password%
:hub_gitea_console_url: %hub_gitea_console_url%
:hub_gitea_admin_username: %hub_gitea_admin_username%
:hub_gitea_admin_password: %hub_gitea_admin_password%
:hub_bastion_public_hostname: %hub_bastion_public_hostname%
:hub_bastion_ssh_password: %hub_bastion_ssh_password%
:hub_bastion_ssh_user_name: %hub_bastion_ssh_user_name%
:hub_ssh_command: %hub_ssh_command%

:primary_openshift_api_server_url: %primary_openshift_api_server_url%

:primary_openshift_cluster_console_url: %primary_openshift_cluster_console_url%
:primary_openshift_cluster_admin_username: %primary_openshift_cluster_admin_username%
:primary_openshift_cluster_admin_password: %primary_openshift_cluster_admin_password%
:primary_bastion_public_hostname: %primary_bastion_public_hostname%
:primary_bastion_ssh_password: %primary_bastion_ssh_password%
:primary_bastion_ssh_user_name: %primary_bastion_ssh_user_name%
:primary_ssh_command: %primary_ssh_command%

:secondary_openshift_api_server_url: %secondary_openshift_api_server_url%
:secondary_openshift_cluster_console_url: %secondary_openshift_cluster_console_url%
:secondary_openshift_cluster_admin_username: %secondary_openshift_cluster_admin_username%
:secondary_openshift_cluster_admin_password: %secondary_openshift_cluster_admin_password%
:secondary_bastion_public_hostname: %secondary_bastion_public_hostname%
:secondary_bastion_ssh_user_name: %secondary_bastion_ssh_user_name%
:secondary_bastion_ssh_password: %secondary_bastion_ssh_password%
:secondary_ssh_command: %secondary_ssh_command%


== Overview
Welcome to Achieve business continuity with Red Hat OpenShift Container Platform.

Organizations running critical applications on Red Hat OpenShift Container Platform need a business continuity plan for site and regional disasters that goes beyond cluster failover or backup and recovery. Its implementation should provide data resiliency and take into account the application continuous deployment practices as a part of the overall enterprise GitOps strategies.

Disaster recovery (DR) helps an organization to recover and resume business critical functions or normal operations when there are disruptions or disasters.

In this hands on lab you will understand the nuances of how to setup an application to continue during a disaster and recovered on another site/cluster. We will use a real life e-retailer application for a fictitious company called Globex selling goods online. You will learn how to Deploy and setup this application for business continuity.
Further, we will test the data persistency across failover/relocate(failback) scenarios by updating the data in the database. Verify that the data is consistent and available after transition from one site/cluster to another.
Finally, we onboard a sample application to be part of Disaster Recovery strategy and test failover/relocate(failback).This time without any guided information to test your understanding.

[NOTE]
Configuring OpenShift Data Foundation for Regional-DR with Advanced Cluster Management is a Technology Preview feature and is subject to Technology Preview support limitations. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

== Intro

In this workshop, you will learn how to achieve Business Continuity for your applications hosted on Red Hat OpenShift platform. Understand some of the implementation aspects of disaster recovery on Red Hat OpenShift Platform. Persistent storage requirement is key to many application and to achieve disaster recovery for such applications, data replication becomes very important. In this lab we will leverage Red Hat OpenShift Data Foundations Storage.

The lab is divided into 5 main sections (expecting 15 minutes per section, last section may take more or less time depending on how comfortable you are with the previous section understanding):

* Understand the Implementation aspects of the environment.
* Deploy Globex Application on Primary.
* Failover Globex Application on Secondary.
* Relocate Application to Primary (FailBack).
* Import a sample application for Business Continuity using Regional DR we just learned.

[NOTE]
Read the instructions carefully before you execute the commands. There are multiple cluster's involved, ensure that you double check before you execute a specific command or update the UI since username and password for all the cluster's are same.

=== Lab Access

The lab consists of three Red Hat OpenShift Clusters.

* Hub Cluster
* Primary Cluster
* Secondary Cluster

You can access your Hub environment bastion server as {hub_bastion_ssh_user_name} with password {hub_bastion_ssh_password} with the following command:

ssh {hub_bastion_ssh_user_name}@{hub_bastion_public_hostname}

[NOTE]
You can use the terminal window on the right side for command line access. For Console UI, kindly open a browser link and open the link there. Do not use the Console tab on the right side of your lab instruction link for this lab. Ensure that you use `htpasswd_provide` to login to OpenShift Console across all cluster's for all the lab modules.

=== Workshop Information
The lab guide here will be your friend to follow through the lab.
Incase you want to explore more, the following information would be userful.

Informational messages generated for your workshop below can be used to access the respective Cluster's incase you want to explore more after the completion of all the lab modules :

=== Hub Cluster Information
Hub Cluster API URL - link:{hub_openshift_api_server_url}[OpenShift Hub Console API]

Hub Cluster Cluster Console URL - link:{hub_openshift_cluster_console_url}[OpenShift Hub Console URL]

Hub Cluster admin - {hub_openshift_cluster_admin_username}

Hub Cluster admin password - {hub_openshift_cluster_admin_password}

Hub Cluster bastion host - {hub_bastion_public_hostname}

Hub Cluster bastion ssh password - {hub_bastion_ssh_password}

Hub Cluster bastion ssh username - {hub_bastion_ssh_user_name}

Hub Cluster ssh command information - {hub_ssh_command}

=== Primary Cluster Information
Primary Cluster API URL - link:{primary_openshift_api_server_url}[OpenShift Primary Cluster API]

Primary Cluster Cluster Console URL - link:{primary_openshift_cluster_console_url}[OpenShift Primary Console URL]

Primary Cluster admin - {primary_openshift_cluster_admin_username}

Primary Cluster admin password - {primary_openshift_cluster_admin_password}

Primary Cluster bastion host - {primary_bastion_public_hostname}

Primary Cluster bastion ssh password - {primary_bastion_ssh_password}

Primary Cluster bastion ssh username - {primary_bastion_ssh_user_name}

Primary Cluster ssh command information - {primary_ssh_command}

=== Secondary Cluster Information
Secondary Cluster API URL - link:{secondary_openshift_api_server_url}[OpenShift Secondary Cluster API]

Secondary Cluster Cluster Console URL - link:{secondary_openshift_cluster_console_url}[OpenShift Secondary Console URL]

Secondary Cluster admin - {secondary_openshift_cluster_admin_username}

Secondary Cluster admin password - {secondary_openshift_cluster_admin_password}

Secondary Cluster bastion host - {secondary_bastion_public_hostname}

Secondary Cluster bastion ssh password - {secondary_bastion_ssh_user_name}

Secondary Cluster bastion ssh username - {secondary_bastion_ssh_password}

Secondary Cluster ssh command information - {secondary_ssh_command}
